apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: demo-stable-policies-placement
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: env
        operator: In
        values:
          - "dev"
